### PR TITLE
71 configuring the patching tool

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Csaba, 

Here's the 3rd part of the updated Patching Docs for 7.1.

Thanks!

https://issues.liferay.com/browse/LRDOCS-5394 Configuring the Patching Tool

### CODE REVIEW

**Comment by CsabaTurcsan** [comment]
Just started reviewing :) <br><br>:muscle: *Sent from [GH](http://nodegh.io).*

**Comment by CsabaTurcsan** [comment]
Hi @jhinkey , in file 03-configuring-the-patching-tool\02-patching-tool-advanced-configuration.markdown, in the proxy setup action, it says:
"Use the following settings to configure your proxy: " then comes our company private IP address. It can sound for new customers that they should use that IP address, which is wrong. This address can be also found in the PT source code, so that should be changed too. By changing, it can be just a note, for example proxy.http.host=<PROXY_IP_ADDRESS>. What do you think?

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan , that's a good idea. I force pushed that change. Let me know what you think. Thanks.

**Comment by CsabaTurcsan** [comment]
Thanks @jhinkey ! If those are the commonly used port numbers, then it is OK!

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan , I left the port numbers but mention replacing them `... and replace the port numbers with yours`

How is that?

**Comment by CsabaTurcsan** [comment]
@jhinkey looks good!

**Comment by jhinkey** [comment]
Great! Sent https://github.com/sez11a/liferay-docs/pull/3237

**Pull request closed without merging**
