### PR TITLE
71 using the patching tool

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Csaba, 

This is the 2nd of 4 sections of the Patching Liferay articles.

https://issues.liferay.com/browse/LRDOCS-5395

### CODE REVIEW

**Comment by CsabaTurcsan** [comment]
Just started reviewing :) <br><br>:muscle: *Sent from [GH](http://nodegh.io).*

**Comment by CsabaTurcsan** [comment]
Hi @jhinkey , 
in file 02-working-with-patches.markdown, when you describe the diff functionality, you might want to mention the "html" option, where instead of the console, the result will be shown in a colored html to make it easier to see the changes.

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan !

Can you give an example of using the "html" option? I haven't been able to run it. Thanks!

**Comment by CsabaTurcsan** [comment]
@jhinkey  : patching-tool.bat diff files store1 store2 html

**Comment by jhinkey** [comment]
@CsabaTurcsan Thanks. That helps me understand it better. I pushed a change that mentions the `html` option for diff.

- `html`: Uses HTML to color the differences and write them to a file. 

How is that? Any other changes for this PR?

**Comment by CsabaTurcsan** [comment]
Hi @jhinkey , I think customers need some details :
The html option creates an html file from the diff into folder <patching-tool-home>/diff, with name <store-1-name>-<store-2-name>-[files | source | fixed-issues]-diff.html, where you can see the difference GitHub-like (additions are green, deletions are red).

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan , please see how I wrote the details. Let me know how that is. Thanks.

**Comment by CsabaTurcsan** [comment]
Thanks @jhinkey ! One final thing. The html output can be only used if one of these [source|fixed-issues|files] is selected.

**Comment by jhinkey** [comment]
OK. I specified that the source, files, or fixed-issues option must accompany the html option. And I used the file name that the usage mentions. Let me know thanks.

**Comment by jhinkey** [comment]
... @CsabaTurcsan - I Just pushed the change.

**Comment by CsabaTurcsan** [comment]
Thanks @jhinkey , perfect!

**Comment by jhinkey** [comment]
Super @CsabaTurcsan ! Thanks for the review!!

**Pull request closed without merging**
