### PR TITLE
71 patching basics

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Csaba!

This is the first installment of DXP Patching articles updated for 7.1.

Would you do the honors of reviewing them?

https://issues.liferay.com/browse/LRDOCS-4771
https://issues.liferay.com/browse/LRDOCS-5393

### CODE REVIEW

**Comment by CsabaTurcsan** [comment]
Just started reviewing :) <br><br>:muscle: *Sent from [GH](http://nodegh.io).*

**Comment by CsabaTurcsan** [comment]
Hi @jhinkey , my origin hasn't been updated for 2 years I guess and as the diff is too big, GitHub cannot show the file I want to refer. So I'm putting my note here for 01-patching-liferay-dxp\01-patching-basics.markdown : 

"Service packs for the @product@ are released about every two months. The
schedule depends on the need and security fix releases."
Basically it is always a fix pack ending with a 0 (10,20... now 50, etc), so the schedule depends on the actual fix pack number.

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan !

Sorry about your origin going stale. 

So a service pack is a fix pack that ends in 0? Is a service pack created every 10 fix packs? Or can there be any number of fix packs (even more than 10) before the next service pack?

If service pack frequency is dictated by every 10 fix packs, then maybe we should just say that?

thanks,

**Comment by CsabaTurcsan** [comment]
@jhinkey , please see this page - https://grow.liferay.com/share/Smart+Fix+Scheduling+in+DXP+Fix+Packs

"So a service pack is a fix pack that ends in 0? Is a service pack created every 10 fix packs? Or can there be any number of fix packs (even more than 10) before the next service pack?"
Yes,yes and no. The reason for the "no" is that fix packs ending with "0" are all heavy fix packs (also included in the GROW article), so we can't just release it normally as it needs customer attention. In this case it is better to make an SP from it also.

**Comment by jhinkey** [comment]
@CsabaTurcsan , can you review the description updates I made for fix packs and service packs. Note, I didn't go into heavy fix packs at this time.

**Comment by CsabaTurcsan** [comment]
Hey @jhinkey , I wouldn't use the word "risky" for customers. Basically, a "risky" fix means that customers may face issues with their customization, and may need to change their own code as well or even do something with their database.

**Comment by jhinkey** [comment]
Hey @CsabaTurcsan - how's the wording I just submitted for the higher risk changes that can go into SPs? …

`- Higher risk. To mitigate risk, the changes are tested more extensively and 
over longer periods of time.`

**Comment by CsabaTurcsan** [comment]
Just started reviewing :) <br><br>:muscle: *Sent from [GH](http://nodegh.io).*

**Comment by CsabaTurcsan** [comment]
Hey @jhinkey , still can be confusing, as there is no explanation for "risk" here. Customers would think that their product may won't work anymore or something like that.
When we started this "heavy fp project", we thought a "risky" fix would mean "it requires customer attention". So the risk is - if we don't notify customers about these changes, and they do nothing but install the fp, their product may not work at all.

**Comment by jhinkey** [comment]
Hi @CsabaTurcsan , I've taken out mentioning "risk" and instead only mentioning facts of what FP and SP changes require. Let me know what you think.

**Comment by CsabaTurcsan** [comment]
Just started reviewing :) <br><br>:muscle: *Sent from [GH](http://nodegh.io).*

**Comment by CsabaTurcsan** [comment]
@jhinkey ,
"Require extensive and over longer periods of time" - for testing?

**Comment by jhinkey** [comment]
Sorry. "Require more extensive testing."

**Comment by jhinkey** [comment]
Please check the force push

**Comment by CsabaTurcsan** [comment]
Thank you @jhinkey , it is OK for me!

**Comment by jhinkey** [comment]
Thanks! Sent https://github.com/sez11a/liferay-docs/pull/3310

**Pull request closed without merging**
